name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build and deploy
        run: |
          python main.py
          echo 'Dash app built!'
          echo 'Deploying to GitHub Pages...'
          git checkout --orphan gh-pages
          git --work-tree assets/ add --all
          git --work-tree assets/ commit -m "Deploy assets"
          git push origin HEAD:gh-pages --force
          git checkout main
          git branch -D gh-pages
